// Generated by TinyFlow
module FullAdder(
  input  logic cin,
  input  logic b,
  input  logic a,
  output logic cout,
  output logic sum
);
  // Local variables
  // Generated nets
  logic 52w;
  logic 60w;
  logic 41w;
  logic 66w;
  logic 65w;
  logic 44w;
  logic 53w;
  logic 56w;
  logic 57w;
  logic 42w;
  logic 67w;
  logic 43w;
  logic 48w;
  logic 46w;
  logic 59w;
  logic 49w;
  logic 64w;
  logic 51w;
  logic 54w;
  logic 45w;
  logic 47w;
  logic 50w;
  // Generated gates
  NAND2D1 g0 (
    .a1(47w),
    .a2(54w),
    .y(sum)
  );
  NAND2D1 g1 (
    .a1(a),
    .a2(46w),
    .y(47w)
  );
  INVD1 g2 (
    .a(45w),
    .out(46w)
  );
  NAND2D1 g3 (
    .a1(42w),
    .a2(44w),
    .y(45w)
  );
  NAND2D1 g4 (
    .a1(b),
    .a2(41w),
    .y(42w)
  );
  INVD1 g5 (
    .a(cin),
    .out(41w)
  );
  NAND2D1 g6 (
    .a1(43w),
    .a2(cin),
    .y(44w)
  );
  INVD1 g7 (
    .a(b),
    .out(43w)
  );
  NAND2D1 g8 (
    .a1(48w),
    .a2(53w),
    .y(54w)
  );
  INVD1 g9 (
    .a(a),
    .out(48w)
  );
  NAND2D1 g10 (
    .a1(50w),
    .a2(52w),
    .y(53w)
  );
  NAND2D1 g11 (
    .a1(b),
    .a2(49w),
    .y(50w)
  );
  INVD1 g12 (
    .a(cin),
    .out(49w)
  );
  NAND2D1 g13 (
    .a1(51w),
    .a2(cin),
    .y(52w)
  );
  INVD1 g14 (
    .a(b),
    .out(51w)
  );
  NAND2D1 g15 (
    .a1(64w),
    .a2(67w),
    .y(cout)
  );
  NOR2D1 g16 (
    .a1(57w),
    .a2(60w),
    .y(64w)
  );
  INVD1 g17 (
    .a(56w),
    .out(57w)
  );
  NAND2D1 g18 (
    .a1(a),
    .a2(b),
    .y(56w)
  );
  INVD1 g19 (
    .a(59w),
    .out(60w)
  );
  NAND2D1 g20 (
    .a1(b),
    .a2(cin),
    .y(59w)
  );
  INVD1 g21 (
    .a(66w),
    .out(67w)
  );
  INVD1 g22 (
    .a(65w),
    .out(66w)
  );
  NAND2D1 g23 (
    .a1(a),
    .a2(cin),
    .y(65w)
  );
endmodule

