// Generated by TinyFlow
module FullAdder(
  input  logic b,
  input  logic cin,
  input  logic a,
  output logic sum,
  output logic cout
);
  // Local variables
  logic 11w;
  // Generated nets
  logic 45w;
  logic 57w;
  logic 50w;
  logic 54w;
  logic 56w;
  logic 49w;
  logic 39w;
  logic 44w;
  logic 41w;
  logic 37w;
  logic 51w;
  logic 52w;
  logic 38w;
  logic 36w;
  logic 55w;
  logic 42w;
  // Generated gates
  NAND2D1 g0 (
    .a1(37w),
    .a2(39w),
    .y(sum)
  );
  NAND2D1 g1 (
    .a1(a),
    .a2(36w),
    .y(37w)
  );
  INVD1 g2 (
    .a(11w),
    .out(36w)
  );
  NAND2D1 g3 (
    .a1(38w),
    .a2(11w),
    .y(39w)
  );
  INVD1 g4 (
    .a(a),
    .out(38w)
  );
  NAND2D1 g5 (
    .a1(49w),
    .a2(52w),
    .y(cout)
  );
  NOR2D1 g6 (
    .a1(42w),
    .a2(45w),
    .y(49w)
  );
  INVD1 g7 (
    .a(41w),
    .out(42w)
  );
  NAND2D1 g8 (
    .a1(a),
    .a2(b),
    .y(41w)
  );
  INVD1 g9 (
    .a(44w),
    .out(45w)
  );
  NAND2D1 g10 (
    .a1(b),
    .a2(cin),
    .y(44w)
  );
  INVD1 g11 (
    .a(51w),
    .out(52w)
  );
  INVD1 g12 (
    .a(50w),
    .out(51w)
  );
  NAND2D1 g13 (
    .a1(a),
    .a2(cin),
    .y(50w)
  );
  NAND2D1 g14 (
    .a1(55w),
    .a2(57w),
    .y(11w)
  );
  NAND2D1 g15 (
    .a1(b),
    .a2(54w),
    .y(55w)
  );
  INVD1 g16 (
    .a(cin),
    .out(54w)
  );
  NAND2D1 g17 (
    .a1(56w),
    .a2(cin),
    .y(57w)
  );
  INVD1 g18 (
    .a(b),
    .out(56w)
  );
endmodule

